name: "SognoDiGhast"
version: "${projectVersion}"
main: "me.kaeternn.sognodighast.SognoDiGhast"
api-version: "1.21"
authors: [Kaeternn]
contributors: []
depend: []
softdepend: []
commands:
  sdg:
    description: "General commands of SognoDiGhast"
    usage: "/sdg [version|reload]"
    permission: sognodighast.admin
    permission-message: You do not have <permission>
permissions:
  sognodighast.admin:
    description: "Allows the player to use /sognodighast command."
    default: op

